dist: xenial
language: python
cache: pip

matrix:
  include:
    - python: "3.7"
      env: PYTHONVER=3

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - graphviz
      - libsnappy-dev

  homebrew:
    update: true
    packages:
      - python
      - graphviz
      - snappy

install: 
  - python3 -m pip install -e .[dev]
  - python3 -m pip install -U --target=`pwd` --no-deps pyEX  # install latest pyEX base
  - git checkout pyEX/caching # the above install clobbers source, so restore

script:
  - make tests
  - make lint

after_success:
    - codecov --token f83b766b-652a-4ddc-858a-a94390c19046

branches:
  only:
  - master

notifications:
  email: false
