dist: xenial
language: python
cache: pip

matrix:
  include:
    - python: "3.7"
      env: PYTHONVER=3

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - graphviz
  homebrew:
    update: true
    packages:
      - python
      - graphviz
      - python2

install: 
  - python3 -m pip install -r requirements.txt && python3 -m pip install -e .[dev]

script: make test

after_success:
    - codecov --token f83b766b-652a-4ddc-858a-a94390c19046

branches:
  only:
  - master

notifications:
  email: false
